language: php
php:
  - 7.1.9
os:
  - linux
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - composer install --dev
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - php artisan migrate --database="testing"
  - php phpunit.phar --version
script:
  - travis_wait php phpunit.phar
after_success:
    - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: "N+Hy8aU43qWhk3p2U/9Buve/qyTWhOCz+fpSv7uJdpHTUHJnOICrrQpdyDU00pj4HXmh2TgJblVeiwcxfXEETAJAulfRfaGVUQYjJj38K8o5uDZtYQ5jXm5Kp2lB6URh5/61BHGQlHW+S850qx3f5rJaXaVKnEUsaeiMKESu7+viy8Vh9sRGQKPBiB2s1N/EYBzhPfkGGb55HMF96rYOogg+ADCbJxzuOYDrUoPg6YM/6+xqvorJxohTOvMggthWDzs/XnGRbZNcAqbpsSVpv79XvykV0IdNjG30YSQtqyJICwZGpWxd7YAq4ldQYf5HEIlOB+jlGaDq7IMzsaCwFBlIS9b4J7KCKX0gfImAyL3ECPwaD45m3fvYXGUVCvNFwfTEDt29WYaNi7X/XRm4dTl7b+2t+lRsGYg1L6IopQqtAfBVkhMCLEzvUzTCvaxyXAU/fUzaCnraCK2dzLfcA98weuwXSG8jUe8cAfztXL8JLd831hxXx51mP+rjxwbCo5u54CFCm02ak8P/xwphrcglVFEB98LTfyKVSets8MO5b/9bYTvdMS4hns+lpZlSgSmdpc/9NKHlrA48rq7LgRdAuk6Hbffr4rzoB+IayJKFkq9d8FekW+jZsvi9K6AkTMeI/t7s1QN0Hr5JAk8sYOvuEnixn2lZtJxehGoi6Ig="
  run:
    - "composer install"
    - "php artisan migrate"
  app: api-cotama
  on:
    repo: Ealenn/Cotama-API
